# Generated by Django 2.1.4 on 2018-12-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='آدرس دفتر مرکزی', max_length=150, verbose_name='Address')),
                ('telehpone', models.CharField(help_text='تلفن دفتر مرکزی', max_length=12, verbose_name='Telephone')),
                ('email', models.EmailField(help_text='ایمیل دفتر مرکزی', max_length=254, verbose_name='Email')),
                ('postalcode', models.CharField(help_text='کد پستی دفتر مرکزی', max_length=10, verbose_name='PostalCode')),
            ],
            options={
                'verbose_name': 'Website Sttiings',
                'verbose_name_plural': 'Website Sttiings',
            },
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Subscription Type', 'verbose_name_plural': 'Subscription Type'},
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='discount_fee',
            field=models.FloatField(help_text='فقط مقدار عددی میزان تخفیف را وارد کنید'),
        ),
    ]
