# Generated by Django 2.1.4 on 2018-12-24 11:28

from django.db import migrations, models
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
    ]
