# Generated by Django 2.1.4 on 2018-12-25 08:22

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20181224_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='roles',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
